# Generated by Django 4.2.4 on 2023-08-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('master', 'Mater'), ('salon', 'Salon')], max_length=10, null=True),
        ),
    ]
