# Generated by Django 4.2.4 on 2023-09-04 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='', verbose_name='About me'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='salons_and_masters',
            field=models.ManyToManyField(blank=True, related_name='profile_salons_and_masters', to=settings.AUTH_USER_MODEL, verbose_name='Salons/Masters'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
