# Generated by Django 4.2.4 on 2024-02-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_phone_number_profile_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posted_in_journal',
            field=models.BooleanField(default=False, verbose_name='Posted in Journal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trusted_mentor',
            field=models.BooleanField(default=False, verbose_name='A trusted mentor/salon'),
        ),
    ]
