version: "3.3"

services:
  web:
    image: ghcr.io/vean-tattoo/tattoolog-backend:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - .:/code
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db

  db:
    image: postgres:15.3
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${PG_DATABASE}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: