version: "3.3"

services:
  web:
    image: ghcr.io/vean-tattoo/tattoolog-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:${WEB_PORT}
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8200:8200"
    depends_on:
      - db

  db:
    image: postgres:15.3
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${PG_DATABASE:-db_log}"
      POSTGRES_USER: "${PG_USER:-db_log_user}"
      POSTGRES_PASSWORD: "${PG_PASSWORD:-passwordb123}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
