# Generated by Django 4.2.4 on 2023-09-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_profile_about_profile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Social media name')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Social media link')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_profile', to='accounts.profile')),
                ('social_media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_type', to='tools.socialmediatype')),
            ],
        ),
    ]
