# Generated by Django 4.2.4 on 2023-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Social media link'),
        ),
    ]
