# Generated by Django 4.2.4 on 2023-09-25 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image to be displayed in the blog post body, card photo and opengraph image', upload_to='blog_images/', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Blog title')),
                ('body', models.TextField(verbose_name='Blog body')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.CharField(help_text='Page name in url. Example: https://domain.com/blog/[my_slug]/', max_length=32, verbose_name='Slug')),
                ('meta_title_tag', models.CharField(help_text='Clickable page title displayed in search engine results as a headline', max_length=255, verbose_name='Meta title tag')),
                ('meta_description', models.CharField(help_text='Description displayed beneath the headline in search engine results', max_length=255, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(help_text='List of keywords that correspond to the content of a website page', max_length=255, verbose_name='Meta keywords')),
                ('opengraph_title', models.CharField(help_text='The title of your object as it should appear within the graph', max_length=255, verbose_name='Opengraph title')),
                ('opengraph_description', models.CharField(help_text='A one to two sentence description of your object', max_length=255, verbose_name='Opengraph description')),
            ],
        ),
    ]
