# Generated by Django 4.2.4 on 2023-11-07 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image to be displayed in the festival post body, card photo and opengraph image', upload_to='festival_images/', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Festival title')),
                ('about', models.TextField(verbose_name='About festival')),
                ('rules', models.TextField(blank=True, default='', verbose_name='Festival rules')),
                ('slug', models.CharField(help_text='Page name in url. Example: https://domain.com/festival/[my_slug]/', max_length=32, verbose_name='Slug')),
                ('date_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('form_url', models.URLField(verbose_name='Link to registration form')),
            ],
        ),
    ]
