# Generated by Django 4.2.4 on 2023-11-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_associationtype'),
        ('tools', '0006_festival'),
    ]

    operations = [
    ]
