# Generated by Django 4.2.4 on 2023-12-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_blogbody_blogbodyphoto_blogmeta_blogphotocarousel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
