# Generated by Django 4.2.4 on 2023-12-28 12:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_blogpost_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogbody',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Blog body'),
        ),
    ]
