# Generated by Django 4.2.4 on 2024-01-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_alter_blogbody_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogbodyphoto',
            name='alt_name',
            field=models.CharField(blank=True, help_text='ALT name for photo', max_length=255, null=True, verbose_name='Photo ALT name'),
        ),
        migrations.AlterField(
            model_name='blogbodyphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog_body/photo', verbose_name='Blog photo'),
        ),
        migrations.AlterField(
            model_name='blogmeta',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description displayed beneath the headline in search engine results', max_length=255, null=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='blogmeta',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='List of keywords that correspond to the content of a website page', max_length=255, null=True, verbose_name='Meta keywords'),
        ),
        migrations.AlterField(
            model_name='blogmeta',
            name='meta_title_tag',
            field=models.CharField(blank=True, help_text='Clickable page title displayed in search engine results as a headline', max_length=255, null=True, verbose_name='Meta title tag'),
        ),
        migrations.AlterField(
            model_name='blogmeta',
            name='opengraph_description',
            field=models.CharField(blank=True, help_text='A one to two sentence description of your object', max_length=255, null=True, verbose_name='Opengraph description'),
        ),
        migrations.AlterField(
            model_name='blogmeta',
            name='opengraph_image',
            field=models.ImageField(blank=True, help_text='Image to be displayed on the opengraph image', null=True, upload_to='opengraph_images/', verbose_name='Opengraph image'),
        ),
        migrations.AlterField(
            model_name='blogmeta',
            name='opengraph_title',
            field=models.CharField(blank=True, help_text='The title of your object as it should appear within the graph', max_length=255, null=True, verbose_name='Opengraph title'),
        ),
        migrations.AlterField(
            model_name='blogphotocarousel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog_carousel/photo', verbose_name='Photo carousel'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Image to be displayed in the blog post body and card photo', null=True, upload_to='blog_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='image',
            field=models.ImageField(blank=True, help_text='Image to be displayed in the festival post body, card photo and opengraph image', null=True, upload_to='festival_images/', verbose_name='Image'),
        ),
    ]
