# Generated by Django 4.2.4 on 2024-01-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_alter_blogbodyphoto_alt_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='type',
            field=models.CharField(choices=[('store', 'Store'), ('project', 'Project')], default='project', max_length=10),
        ),
    ]
