# Generated by Django 4.2.4 on 2024-01-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_partners_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='about_de',
            field=models.TextField(null=True, verbose_name='About festival'),
        ),
        migrations.AddField(
            model_name='festival',
            name='about_en',
            field=models.TextField(null=True, verbose_name='About festival'),
        ),
        migrations.AddField(
            model_name='festival',
            name='about_pl',
            field=models.TextField(null=True, verbose_name='About festival'),
        ),
        migrations.AddField(
            model_name='festival',
            name='about_uk',
            field=models.TextField(null=True, verbose_name='About festival'),
        ),
        migrations.AddField(
            model_name='festival',
            name='rules_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Festival rules'),
        ),
        migrations.AddField(
            model_name='festival',
            name='rules_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Festival rules'),
        ),
        migrations.AddField(
            model_name='festival',
            name='rules_pl',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Festival rules'),
        ),
        migrations.AddField(
            model_name='festival',
            name='rules_uk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Festival rules'),
        ),
    ]
