# Generated by Django 4.2.4 on 2024-01-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_festival_about_de_festival_about_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='country',
            field=models.CharField(choices=[('en', 'England'), ('de', 'Germany'), ('pl', 'Poland'), ('ua', 'Ukraine')], default='pl', max_length=10),
        ),
    ]
