# Generated by Django 4.2.4 on 2024-01-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_festival_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About festival'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='about_de',
            field=models.TextField(blank=True, null=True, verbose_name='About festival'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About festival'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='about_pl',
            field=models.TextField(blank=True, null=True, verbose_name='About festival'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='about_uk',
            field=models.TextField(blank=True, null=True, verbose_name='About festival'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='form_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link to registration form'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Festival title'),
        ),
    ]
