# Generated by Django 4.2.4 on 2024-01-11 15:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_alter_festival_about_alter_festival_about_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About festival'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='about_de',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About festival'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='about_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About festival'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='about_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About festival'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='about_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='About festival'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='rules',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Festival rules'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='rules_de',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Festival rules'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='rules_en',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Festival rules'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='rules_pl',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Festival rules'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='rules_uk',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Festival rules'),
        ),
    ]
