# Generated by Django 4.2.4 on 2024-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_alter_festival_about_alter_festival_about_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(blank=True, null=True, verbose_name='Social media link'),
        ),
    ]
