# Generated by Django 4.2.4 on 2024-01-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_blogcategory_blogpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Festival category name')),
            ],
            options={
                'verbose_name': 'Festival category',
                'verbose_name_plural': 'Festival categories',
            },
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Blog category', 'verbose_name_plural': 'Blog categories'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AddField(
            model_name='festival',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='festival_category', to='tools.festivalcategory'),
        ),
    ]
