# Generated by Django 4.2.4 on 2024-02-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogbody',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='blogbodyphoto',
            options={'ordering': ['id']},
        ),
    ]
