# Generated by Django 4.2.4 on 2024-02-20 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0021_alter_blogbody_options_alter_blogbodyphoto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalPhotoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='festival_submission_images/', verbose_name='Image')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_submissions', to='tools.festival')),
            ],
        ),
        migrations.CreateModel(
            name='FestivalPhotoVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateField(auto_now_add=True)),
                ('voter_ip', models.GenericIPAddressField(verbose_name='Voter IP')),
                ('photo_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tools.festivalphotosubmission')),
            ],
            options={
                'unique_together': {('photo_submission', 'voter_ip', 'voted_at')},
            },
        ),
    ]
