# Generated by Django 4.2.4 on 2023-09-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='Work type name'),
        ),
    ]
