# Generated by Django 4.2.4 on 2023-09-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_worktype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='portfolio/photo', verbose_name='Post photo'),
        ),
    ]
