# Generated by Django 4.2.4 on 2023-11-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_count_visit'),
        ('tools', '0006_associationtype'),
        ('portfolio', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='pending', help_text="Status of consideration of the association's label", max_length=10)),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_profile_associate', to='accounts.profile')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_type', to='tools.associationtype')),
            ],
        ),
        migrations.CreateModel(
            name='AssociationPhotoProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='proof/photo', verbose_name='Association photo proof')),
                ('moderation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_proof_moderation', to='portfolio.moderationassociation')),
            ],
        ),
    ]
