# Generated by Django 4.2.4 on 2024-01-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_project'),
        ('accounts', '0013_remove_profile_phone_number_profile_mentor_and_more'),
        ('portfolio', '0005_worktype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationFromProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='pending', help_text='Status of consideration', max_length=10)),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_profile_from_project', to='accounts.profile')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='tools.project')),
            ],
        ),
    ]
